psico/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import PasswordChangeDoneView
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('register/', register_1, name='register_1'),
    path('register/step-2/', register_2, name='register_2'),
    path('logout/', logout_view, name="logout"),
    path('__debug__/', include('debug_toolbar.urls')),
    path('get_cities/<int:region_id>/', get_cities, name='get_cities'),
    path('login/', login_view, name='login'),
    path('home/', home, name='home'),
    path('buscar/', buscar, name='buscar'),
    path('agendamento/', agendamento, name='agendamento'),
    path('agendamento/<uuid:uuid>/', agendamento, name='agendamento'),
    path('confirmado/<uuid:confirmation_token>/', confirmado, name='confirmado'),
    path('perfil/<uuid:user_uuid>/', perfil, name='perfil'),
    path('atualizar_notas/<int:agendamento_id>/', atualizar_notas, name='atualizar_notas'),
    path('cancelar_agendamento/<int:agendamento_id>/', cancelar_evento, name='cancelar_evento'),
    path('editar_perfil/', editar_perfil, name='editar_perfil'),
    path('mudar_senha/', custom_password_change, name='mudar_senha'),
    path('eventos_json/', eventos_json, name='eventos_json'),
     path('available_terapeutas/', available_terapeutas, name='available_terapeutas'),

    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Permission, Group
import uuid
from cities_light.receivers import connect_default_signals
from cities_light.abstract_models import (AbstractCountry, AbstractRegion, AbstractCity, AbstractSubRegion) 

#Classes for multiple choice fields. Populated from the second migration file.
class PublicoAlvo(models.Model):
    publico = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.publico  
class Linguas(models.Model):
    linguas = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.linguas

class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = [
        ('terapeuta', 'Terapeuta'),
        ('paciente', 'Paciente'),
    ]
    GENDER = [
        ('Masculino', 'Masculino'),
        ('Feminino', 'Feminino'),
        ('Outro/Prefiro não indicar', 'Outro/Prefiro não indicar'),
    ]
    SPECIALIZATION_CHOICES = [
        ('TCC', 'Terapia Cognitivo-Comportamental (TCC)'),
        ('Junguiana', 'Psicologia Analítica (Junguiana)'),
        ('Freudiana', 'Psicanálise Freudiana'),
        ('Lacaniana', 'Psicanálise Lacaniana'),
        ('Humanista', 'Psicologia Humanista'),
        ('Positiva', 'Psicologia Positiva'),
        ('Casal_Familia', 'Terapia de Casal e Família'),
        ('Sistemica', 'Terapia Sistêmica'),
        ('Gestalt', 'Terapia Gestalt'),
        ('Esquema', 'Terapia do Esquema'),
        ('Comportamento', 'Análise do comportamento'),
        ('Outra', 'Outra')
    ]
    
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)
    groups = models.ManyToManyField(Group, related_name='%(app_label)s_%(class)s_groups', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='%(app_label)s_%(class)s_permissions', blank=True)
    nome = models.CharField(max_length=100)
    foto = models.ImageField(upload_to='profile_pictures/', blank=True, null=True, default='https://tse2.mm.bing.net/th?id=OIP.Jw-MfZVo8aCZLEVTHvMZbQHaE8&pid=Api')
    nascimento = models.DateField(blank=True, null=True)
    telefone = models.CharField(max_length=30, blank=True, null=True)
    uuid =  models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.CharField(max_length=50, blank=True, null=True)
    mandar_email = models.BooleanField(blank=True, null = True)
    mandar_whats = models.BooleanField(blank=True, null = True)
    estado = models.CharField(max_length=50, blank=True, null=True)
    cidade = models.CharField(max_length=50, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    preco = models.PositiveIntegerField(default=0, verbose_name='Preço', blank=True, null=True) 
    sexo = models.CharField(max_length=100, choices=GENDER)
    idioma = models.ManyToManyField(Linguas)

    # Terapeuta-specific fields
    especialidade = models.CharField(max_length=100, choices=SPECIALIZATION_CHOICES, blank=True, null=True)
    publico = models.ManyToManyField(PublicoAlvo, blank=True)
    formacao = models.CharField(max_length=100, blank=True, null=True)
    limite_eventos = models.PositiveIntegerField(null=True, blank=True, default=10)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs) 
        if self.pk:
            permission = Permission.objects.get(codename='delete_event', content_type__model=Evento._meta.model_name)
            self.user_permissions.add(permission)

#Necessary to make cities_light work.
class Country(AbstractCountry):
    pass
connect_default_signals(Country)   
class Region(AbstractRegion):
    pass
connect_default_signals(Region)
class SubRegion(AbstractSubRegion):
    pass
connect_default_signals(SubRegion)
class City(AbstractCity):
    timezone = models.CharField(max_length=40)
connect_default_signals(City)

class Evento(models.Model):
    terapeuta = models.ForeignKey(CustomUser, on_delete=models.CASCADE, limit_choices_to={'user_type': 'terapeuta'})
    paciente = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True, limit_choices_to={'user_type': 'paciente'}, related_name='paciente_eventos')
    horario = models.DateTimeField(blank=True, null=True)
    duracao = models.DecimalField(default=0, max_digits=3, decimal_places=0, verbose_name='Duração (min)')
    notas = models.TextField()
    confirmation_token = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    num_occurrences = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        permissions = [
            ("delete_event", ("Pode deletar agendamentos")),
        ]

#When an appointment is requested and a confirmation email is sent, its data is saved here. After confirmation it is deleted and saved into Evento.
class PendingAgendamento(models.Model):
    confirmation_token = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    terapeuta = models.ForeignKey(CustomUser, related_name='pending_terapeuta', on_delete=models.CASCADE)
    paciente = models.ForeignKey(CustomUser, related_name='pending_paciente', on_delete=models.CASCADE)
    horario = models.DateTimeField(blank=True, null=True)
    duracao = models.DecimalField(default=0, max_digits=3, decimal_places=0, verbose_name='Duração (min)')
    notas = models.TextField(blank=True, null=True)
    num_occurrences = models.PositiveIntegerField(null=True, blank=True)

app/forms.py
from django import forms
from .models import *
from .utils import *
from django.forms import widgets
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserChangeForm, AuthenticationForm, PasswordChangeForm
from crispy_forms.layout import Layout, Submit, Button, Row, Column
from crispy_bootstrap5.bootstrap5 import FloatingField, Field
from django.core.validators import MinValueValidator,MaxValueValidator
from django.forms import ModelMultipleChoiceField
from crispy_forms.helper import FormHelper

class RegionChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name

#First registration page
class UserTypeForm(forms.Form):
    #Fields
    user_type = forms.ChoiceField(choices=[('terapeuta', 'Terapeuta'), ('paciente', 'Paciente')], widget=forms.RadioSelect, required=True)
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    
    #Defining layout and texts
    def __init__(self, *args, **kwargs):
        super(UserTypeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.fields['password1'].label = 'Senha'
        self.fields['password1'].help_text = None
        self.fields['password2'].label = 'Confirme a nova senha'
        self.fields['password2'].help_text = None
        self.helper.add_input(Submit('submit', 'Salvar', css_class='btn btn-primary'))
        self.helper.layout = Layout(
            Row(
            Column(FloatingField('username', css_class='form-control mb-3')),
            Column(FloatingField('email', css_class='form-control mb-3'))),
            Row(
            Column(FloatingField('password1', css_class='form-control mb-3')),
            Column(FloatingField('password2', css_class='form-control mb-3'))
            ))
        self.error_messages = {
            'password_incorrect': _("Senha atual incorreta. Por favor, insira novamente."),
            'password_mismatch': _("As senhas não coincidem."),
            'password_too_short': _("A senha é muito curta."),
            'password_too_common': _("A senha é muito comum."),
            'password_entirely_numeric': _("A senha não pode ser inteiramente numérica."),
            'password_incorrect': _("Senha atual incorreta. Por favor, insira novamente."),
        }

class RegisterForm(forms.ModelForm):
    nome = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    nascimento = forms.DateField(required=True, input_formats=['%d/%m/%Y'], widget=forms.DateInput(attrs={'class': 'form-control', 'id': 'id_nascimento'}))
    telefone = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    cidade = forms.ModelChoiceField(queryset=City.objects.all().order_by('name'), required=False, label='Cidade', widget=forms.Select(attrs={'class': 'form-select'}))
    estado = RegionChoiceField(queryset=Region.objects.all().order_by('name'), required=True, label='Estado', widget=forms.Select(attrs={'class': 'form-select'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'bio-field'}), required=False, )
    preco = forms.DecimalField(max_digits=20, decimal_places=2, required=False, label='Preço', validators=[MinValueValidator(0),MaxValueValidator(100)], widget=forms.NumberInput(attrs={'class': 'form-control', 'step':'5', 'id': 'preco-widget'}))
    sexo = forms.ChoiceField(choices=CustomUser.GENDER, required=True, label='Sexo', widget=forms.Select(attrs={'class': 'form-select'}))
    idioma = ModelMultipleChoiceField(queryset=Linguas.objects.all(), label='Idioma de preferência', required=False, widget=forms.SelectMultiple(attrs={'class': 'form-select'}))
    profile_picture = forms.ImageField(required=False, label="Foto do perfil", widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
    especialidade = forms.ChoiceField(choices=CustomUser.SPECIALIZATION_CHOICES, required=False, label='Linha Teórica', widget=forms.Select(attrs={'class': 'form-select'}))
    publico = ModelMultipleChoiceField(queryset=PublicoAlvo.objects.all(), label="Público Alvo", required=False, widget=forms.SelectMultiple(attrs={'class': 'form-select'}))
    formacao = forms.CharField(max_length=100, required=False, label='Formação Acadêmica', widget=forms.TextInput(attrs={'class': 'form-control'}))
    limite_eventos = forms.IntegerField(required=False, label='Limite mensal de agendamentos')
    mandar_email = forms.BooleanField(required=False, label = "Permissão para que enviemos emails")
    mandar_whats = forms.BooleanField(required=False, label = "Permissão para que enviemos mensagens de WhatsApp")

    def clean(self):
        cleaned_data = super().clean()
        mandar_email = cleaned_data.get('mandar_email')
        mandar_whats = cleaned_data.get('mandar_whats')

        if not (mandar_email or mandar_whats):
            raise ValidationError("É necessário selecionar pelo menos uma opção de contato (email ou WhatsApp)")

        return cleaned_data

    class Meta:
        model = CustomUser
        exclude = ('password1', 'password2') 
        fields = ('nome', 'nascimento', 'telefone', 'limite_eventos', 'estado', 'cidade', 'bio', 'preco', 'sexo', 'idioma', 'profile_picture', 'especialidade', 'publico', 'formacao')
    
    def __init__(self, user_type=None, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user_type = user_type
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.fields['mandar_email'].help_text = "Selecione pelo menos uma opção. Enviamos somente confirmações de consultas"
        common_fields = [
                FloatingField('nome', css_class='form-group-sm mb-3'),
                Field('bio', css_class='form-group-sm mb-3'),
            Row(
                Column(FloatingField('nascimento', css_class='form-group-sm col-md-2 mb-3')),
                Column(FloatingField('sexo', css_class='form-group-sm col-md-2 mb-3')),
                Column(FloatingField('telefone', css_class='form-group-sm col-md-2 mb-3')),
            ),
            Row(
                Column(FloatingField('estado', css_class='form-group-sm col-md-6 mb-3')),
                Column(FloatingField('cidade', css_class='form-group-sm col-md-6 mb-3')),
            ),
            Row(
                Column(Field('idioma', css_class='form-group-sm col-md-3 mb-3 js-select2')),
                Column(Field('preco', css_class='form-group-sm col-md-3 mb-3')),
                Column(Field('profile_picture', css_class='form-group-sm col-md-3 mb-3')),
            Row(
                Column(Field('mandar_email', css_class='form-group-sm mb-3'), css_class='col-md-6'),
                Column(Field('mandar_whats', css_class='form-group-sm mb-3'), css_class='col-md-6'))
            )
        ]
                
        terapeuta_fields = [
            Row(
        Column(Field('especialidade', css_class='form-group-sm mb-3'), css_class='col-md-3'),
        Column(Field('publico', css_class='form-group-sm mb-3 js-select2'), css_class='col-md-3'),
        Column(Field('formacao', css_class='form-group-sm mb-3'), css_class='col-md-3'),
        Column(Field('limite_eventos', css_class='form-group-sm mb-3'), css_class='col-md-3'),
    ),]

        #Show different fields and texts according to user_type
        if user_type == 'terapeuta':
            layout_fields = common_fields + terapeuta_fields
            self.fields['preco'].label = 'Preço de sua consulta. Valor entre R$ 5 e R$70'
            self.fields['bio'].label = 'Conte um pouco sobre você e seu trabalho'
            self.fields['idioma'].label='Idiomas'
        else:
            layout_fields = common_fields
            self.fields['preco'].label = 'Valor que está disposto a pagar por uma consulta. Valor entre R$ 5 e R$70'
            self.fields['bio'].label = 'Conte pouco sobre você e seu histórico de saúde mental. Importante mencionar se toma algum medicamento.'
            self.fields['idioma'].label='Idioma de preferência'

        self.helper.layout = Layout(*layout_fields)
        self.helper.add_input(Submit('submit', 'Registrar', css_class='btn btn-primary btn-lg'))
        self.helper.add_input(Button('cancel', 'Cancelar', css_class='btn btn-outline-secondary btn-lg'))

class SearchForm(forms.Form):
    cidade = forms.ModelChoiceField(queryset=City.objects.none(), required=False, label='Cidade', widget=forms.Select(attrs={'class': 'form-select'}))
    estado = RegionChoiceField(queryset=Region.objects.all().order_by('name'), required=False, label='Estado', widget=forms.Select(attrs={'class': 'form-select'}))
    max_preco = forms.DecimalField(max_digits=20, decimal_places=0, required=False, label='Valor máximo R$', widget=forms.NumberInput(attrs={'class': 'form-control'}))
    especialidade = forms.ChoiceField(choices= [('', 'Qualquer')] + CustomUser.SPECIALIZATION_CHOICES, required=False, label='Linha Teórica', widget=forms.Select(attrs={'class': 'form-select ','data-placeholder': ''}))
    sexo = forms.ChoiceField(choices=[('', 'Qualquer')] + CustomUser.GENDER, required=False, label='Gênero', widget=forms.Select(attrs={'class': 'form-select', 'data-placeholder': ''}))
    min_idade = forms.IntegerField(required=False, label="Idade mínima", widget=forms.NumberInput(attrs={'class': 'form-control'}))
    max_idade = forms.IntegerField(required=False, label="Idade máxima", widget=forms.NumberInput(attrs={'class': 'form-control'}))

app/templates/busca.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %} 


<main>
    
    
<div class="container">
    <h1 class="my-4">Buscar {% if user_type == 'paciente' %} terapeutas {% else %} pacientes {% endif %}</h1>
    <form method="get" id="searchForm" class="mb-3">
      {% crispy form %}
    </form>

    <h2 class="my-4">Resultados</h2>
    {% if target %}
    <table class="table table-striped">
      <thead>
  {% for header in columns %}
          <th>{{ header|capfirst }}
            <a href="#" class="sorting-link" data-header="{{ header }}" onclick="sortTable(event)">
              <i class="fa-solid fa-filter {% if sort_by == header %}{% if order == 'asc' %}text-primary{% else %}text-secondary{% endif %}{% else %}text-dark{% endif %}"></i>
            </a></th>
  {% endfor %}
        </thead>

      <tbody id="results-table-body">
        {% for user in target %}
        <tr>
          <td><a href="{% url 'perfil' user.uuid %}">{{ user.nome }}</a></td>
          <td>{{ user.sexo }}</td>
          <td>{{ user.idade }}</td>
          <td>{% for idioma in user.idioma.all %}{{ idioma }}
            {% if not forloop.last%}, {% endif %}{% endfor %}</td>
          <td>{{ user.estado }}</td>
          <td>{{ user.cidade }}</td>
          {% if user_type == 'paciente' %}
          <td>{{ user.especialidade }}</td>
          <td>{% for publico in user.publico.all %}{{ publico }}
            {% if not forloop.last %}, {% endif %}{% endfor %}</td>
          <td>{{ user.formacao }}</td>
          {% endif %}
          <td>R$ {{ user.preco }}</td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="5">Nenhum resultado encontrado.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
</div>
</main>

<!-- Populate the city dropdown according to selected state -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
    const regionSelect = document.querySelector('#id_estado');
    const citySelect = document.querySelector('#id_cidade');

    regionSelect.addEventListener('change', function() {
      const regionId = this.value;

      fetch(`/get_cities/${regionId}/`)
        .then(response => response.json())
        .then(cities => {
          // Clear the city select options
          citySelect.innerHTML = '';

          // Add a default empty option
          const defaultOption = document.createElement('option');
          defaultOption.value = '';
          defaultOption.text = '---------';
          citySelect.add(defaultOption);

          // Populate the city select with new options
          cities.forEach(city => {
            const option = document.createElement('option');
            option.value = city.id;
            option.text = city.name;
            citySelect.add(option);
          });
        });
    });
  });

//Define sorting behavior
function sortTable(event) {
    event.preventDefault();
    const link = event.target.closest('.sorting-link');
    const header = link.dataset.header;
    const icon = link.children[0];

    const url = new URL(window.location);

    let currentOrder = url.searchParams.get('order');
    let currentSortBy = url.searchParams.get('sort_by');

    let newOrder = '';
    if (currentSortBy === header) {
        if (currentOrder === 'asc') {
            newOrder = 'desc';
        } else if (currentOrder === 'desc') {
            newOrder = '';
        } else {
            newOrder = 'asc';
        }
    } else {
        newOrder = 'asc';
    }

    icon.classList.remove('text-primary', 'text-secondary', 'text-dark');
    icon.classList.add(newOrder === 'asc' ? 'text-primary' : newOrder === 'desc' ? 'text-secondary' : 'text-dark');

    if (newOrder === '') {
        url.searchParams.delete('sort_by');
        url.searchParams.delete('order');
    } else {
        url.searchParams.set('sort_by', header);
        url.searchParams.set('order', newOrder);
    }
    window.location = url.toString();
}




//Populate field with placeholders
document.addEventListener('DOMContentLoaded', function() {
        $('.selectmultiple').select2();
    });

</script>
{% endblock content %}

app/templates/cancelamento.html
{% autoescape off %}
<!DOCTYPE html>

<htmllang="en">
<head>
<metacharset="UTF-8"/>
<metaname="viewport"content="width=device-width, initial-scale=1.0"/>
</head>
<body>

    <p>Olá,</p>
    <p>sua consulta com </p>
    <p>{{ self }}<br>
    em {{ agendamento.horario }}<br>
    <p>foi cancelada</p>


</body>
</html>
{% endautoescape %}

app/templates/editar_perfil.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h1>Editar Perfil</h1>
  <div class="row">
    <div class="col-md-12">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.errors }}
        {% crispy form %}
        <div class="form-group">
          <a href="{% url 'mudar_senha' %}" class="btn btn-secondary">Alterar senha</a>
        </div>
      </form>
    </div>
  </div>


<script>

    //Populates the cities field with cities from the selected state
    $(document).ready(function() {
    $('#id_estado').on('change', function() {
        let regionId = $(this).val();
        console.log(regionId);
        if (regionId) {
            $.ajax({
                url: `{% url 'get_cities' 0 %}`.replace('0', regionId),
                success: function(data) {
                    $('#id_cidade').html(optionsForSelect(data));
                    $('#id_cidade').prop('disabled', false);
                }
            });
        } else {
            $('#id_cidade').html('<option value="">Cidade</option>');
            $('#id_cidade').prop('disabled', true);
        }
    });

    function optionsForSelect(data) {
        let options = '<option value="">Select</option>';
        for (let i = 0; i < data.length; i++) {
            options += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
        }
        return options;
    }
    });


//Auto completes the birthday field with /
    $(document).ready(function () {
        $('#id_nascimento').on('input', function () {
            const input = $(this);
            const value = input.val();
            if (/^\d{2}$/.test(value)) {
                input.val(value + '/');
            } else if (/^\d{2}\/\d{2}$/.test(value)) {
                input.val(value + '/');
            }
        });
    });    

  </script>
{% endblock %}

app/templates/mudar_senha.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 

{% block content %}
  <div class="container">
    <h1>Mudar senha</h1>
    <form method="post">
      {% csrf_token %}
      {% crispy form %}
    </form>
  </div>


{% endblock content %}

app/templates/mudar_senha_done.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h1>Senha alterada</h1>
  </div>
{% endblock content %}

app/templates/pedido_agendamento_paciente_whats.html
Olá, {{ agendamento.paciente }}
você recebeu um pedido de agendamento de
{{ agendamento.terapeuta.nome }}
Horario: {{ agendamento.horario }}
Duração: {{ agendamento.duracao }} minutos
Preço da consulta: R$ {{ agendamento.terapeuta.preco }}
Mensagem: {{mensagem}}

Acesse o link para confirmar o agendamento
http://localhost:8000/confirmado/{{ confirmation_token }}

app/templates/register.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{%load crispy_forms_tags %} 

<div class="container">
    <h2>Cadastro</h2>
    <form method="post" class="mt-4" action="{% url 'register' %}">
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>
          


<script>

    // Hides fields that are only for therapists
    var userTypeSelect = document.getElementById('id_user_type');
    const especialidade = document.getElementById('div_id_especialidade');
    const publico = document.getElementById('div_id_publico');
    const formacao = document.getElementById('div_id_formacao');
    therapistFields=[especialidade, publico, formacao]

    
    userTypeSelect.addEventListener('change', () => {
    if (userTypeSelect.value === 'terapeuta') {
        therapistFields.forEach(field => field.classList.remove('d-none'));
    } else {
        therapistFields.forEach(field => field.classList.add('d-none'));
    }
});

    //Populates the cities field with cities from the selected state
    $(document).ready(function() {
    $('#id_estado').on('change', function() {
        let regionId = $(this).val();
        console.log(regionId);
        if (regionId) {
            $.ajax({
                url: `{% url 'get_cities' 0 %}`.replace('0', regionId),
                success: function(data) {
                    $('#id_cidade').html(optionsForSelect(data));
                    $('#id_cidade').prop('disabled', false);
                }
            });
        } else {
            $('#id_cidade').html('<option value="">Cidade</option>');
            $('#id_cidade').prop('disabled', true);
        }
    });

    function optionsForSelect(data) {
        let options = '<option value="">Select</option>';
        for (let i = 0; i < data.length; i++) {
            options += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
        }
        return options;
    }
    });


//Auto completes the birthday field with /
    $(document).ready(function () {
        $('#id_nascimento').on('input', function () {
            const input = $(this);
            const value = input.val();
            if (/^\d{2}$/.test(value)) {
                input.val(value + '/');
            } else if (/^\d{2}\/\d{2}$/.test(value)) {
                input.val(value + '/');
            }
        });
    });    


    //Changes the text on the Bio field depending on user_type
    var bioField = document.getElementById('bio-field');
    
    userTypeSelect.addEventListener('change', function() {
        var selectedUserType = userTypeSelect.value;
        if (selectedUserType === 'terapeuta') {
            bioField.placeholder = 'Digite aqui a sua formação e experiência profissional';
        } else if (selectedUserType === 'paciente') {
            bioField.placeholder = 'Digite aqui uma breve descrição sobre você';
        } else {
            bioField.placeholder = 'Digite aqui';
        }
    });
</script>


        
{% endblock content %}

app/templates/register_2.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{%load crispy_forms_tags %} 

<div class="container">
    <h2>Cadastro</h2>
    <form method="post" class="mt-4" action="{% url 'register_2' %}">
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>


<script>
    //Populates the cities field with cities from the selected state
    $(document).ready(function() {
    $('#id_estado').on('change', function() {
        let regionId = $(this).val();
        console.log(regionId);
        if (regionId) {
            $.ajax({
                url: `{% url 'get_cities' 0 %}`.replace('0', regionId),
                success: function(data) {
                    $('#id_cidade').html(optionsForSelect(data));
                    $('#id_cidade').prop('disabled', false);
                }
            });
        } else {
            $('#id_cidade').html('<option value="">Cidade</option>');
            $('#id_cidade').prop('disabled', true);
        }
    });

    function optionsForSelect(data) {
        let options = '<option value="">Select</option>';
        for (let i = 0; i < data.length; i++) {
            options += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
        }
        return options;
    }
    });


//Auto completes the birthday field with /
    $(document).ready(function () {
        $('#id_nascimento').on('input', function () {
            const input = $(this);
            const value = input.val();
            if (/^\d{2}$/.test(value)) {
                input.val(value + '/');
            } else if (/^\d{2}\/\d{2}$/.test(value)) {
                input.val(value + '/');
            }
        });
    });
    
    

    
</script>


        
{% endblock content %}